# Codecov configuration for nethermind-arbitrum
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        informational: true  # Advisory only - doesn't block PRs (handles edge cases like submodule-only updates)

comment:
  layout: "header,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false

# Ignore non-production code
ignore:
  - "src/Nethermind/**"           # Nethermind submodule (not our code)
  - "**/*.Test/**"                # Test projects
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.Designer.cs"
  - "**/*.generated.cs"
  - "**/Migrations/**"
