coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.Test/**"
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.AssemblyInfo.cs"
  - "**/Program.cs"
  - "**/*.Designer.cs"
  - "**/*.generated.cs"
  - "**/Migrations/**"

flags:
  unittests:
    paths:
      - src/Nethermind.Arbitrum.Test/
    carryforward: true

github_checks:
  annotations: true
