coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

ignore:
  - "**/*.Test/**"
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.AssemblyInfo.cs"
  - "**/Program.cs"
  - "**/*.Designer.cs"
  - "**/*.generated.cs"
  - "**/Migrations/**"
  - "**/Properties/**"
  - "src/Nethermind/**"

flags:
  unittests:
    paths:
      - src/Nethermind.Arbitrum/
    carryforward: true

github_checks:
  annotations: true

pull_request_rules:
  - name: "Coverage decreased"
    conditions:
      - "coverage.patch < 70%"
    actions:
      comment:
        message: |
          ## ⚠️ Coverage Decreased

          This PR decreases coverage below the 70% threshold.
          Please add tests to improve coverage.

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false
