{
 "title": "Nethermind Arbitrum Dashboard",
 "tags": [
  "nethermind",
  "arbitrum",
  "blockchain"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(nethermind_blocks[5m])", "legendFormat": "Blocks per second" }
   ]
  },
  {
   "title": "Total Blocks Processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nethermind_blocks", "legendFormat": "Total Blocks" }
   ]
  },
  {
   "title": "Transaction Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nethermind_transactions[5m])",
     "legendFormat": "Transactions per second"
    }
   ]
  },
  {
   "title": "Gas Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mgas" } },
   "targets": [
    { "expr": "nethermind_mgas_per_sec", "legendFormat": "MGas per second" }
   ]
  },
  {
   "title": "EVM OpCode Execution Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(nethermind_op_codes[5m])", "legendFormat": "OpCodes per second" }
   ]
  },
  {
   "title": "EVM Exceptions Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(nethermind_evm_exceptions[5m])",
     "legendFormat": "EVM Exceptions per second"
    }
   ]
  }
 ]
}