#!/bin/bash
# Session-start hook: Initialize workspace and verify access to both repos

echo "{"
echo "  \"systemMessage\": \"🚀 Arbitrum Dual-Client Workspace Initialized\\n\\n"
echo "📂 Repositories:\\n"
echo "  - Nethermind (C#): /Users/daniilankusin/RiderProjects/nethermind-arbitrum\\n"
echo "  - Nitro (Go): /Users/daniilankusin/GolandProjects/arbitrum-nitro\\n\\n"
echo "🤖 Available Agents:\\n"
echo "  - Task-Orchestrator: Meta-agent for complex tasks (/orchestrate)\\n"
echo "  - Precompile-Validator: Validate precompiles vs Nitro\\n"
echo "  - Cross-Repo-Validator: Validate C# vs Go implementations\\n"
echo "  - State-Root-Debugger: Debug state root mismatches\\n"
echo "  - Nitro-Source-Reader: Read and explain Go source\\n"
echo "  - Implementation-Mapper: Map Go ↔ C# files\\n"
echo "  - Repo-Navigator: Explore codebase (READ-ONLY)\\n\\n"
echo "💡 Quick Commands:\\n"
echo "  - /orchestrate [task]: Invoke orchestrator for complex tasks\\n"
echo "  - /validate-precompile: Validate precompile\\n"
echo "  - /compare-impl: Compare implementations\\n"
echo "  - /state-root-debug: Debug state root issues\\n\\n"
echo "⚠️ Remember: Agents are invoked automatically based on task type and keywords.\\n"
echo "   Use /orchestrate for multi-step workflows.\""
echo "}"
