name: Run Node in Chain

on:
  workflow_dispatch:

permissions: {}

jobs:
  run-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Mock workflow
      - name: Checkout repository
        uses: actions/checkout@v7
